### ISSUE TITLE
To-do list for c-krit/ferox v1.0.0 (rewrite)

### ISSUE THREAD

**Issue by jdeokkim** [c-krit/ferox#12]
- [ ] API Documentation & README.md
- [ ] Makefile compatible with [BSD Make](https://man.freebsd.org/cgi/man.cgi?make(1))
- [ ] Unit tests with the [`greatest.h` library](https://github.com/silentbicycle/greatest)
