### ISSUE TITLE
To-do list for c-krit/ferox v1.0.0 (rewrite)

### ISSUE THREAD

**Issue by jdeokkim** [c-krit/ferox#13]
## Documentation

- [ ] Add a project banner to `docs/static`
- [ ] Add `.github/ISSUE_TEMPLATE/bug_report.md`
- [ ] Update `.github/PULL_REQUEST_TEMPLATE.md`

## Features

- [ ] Add a function for performing a point-in-polygon query
