### ISSUE TITLE
To-do list for v0.3.0

### ISSUE THREAD

**Issue by jdeokkim** [c-krit/ferox#2]
## To-do list for v0.3.0
- [ ] Add `lights` example
- [ ] Implement `frComputeWorldRaycast()` function
- [ ] Remove `stb_ds.h` dependency completely (if possible)
